### ISSUE TITLE
ask for config file

### ISSUE THREAD

**Issue by Wangzz12138** [Sense-X/GeoMIM#1]
Hello, may I ask if the training config file can be made public? I noticed that the existing pretrained config file appears to be for BEVfusion.

**Comment by jihaonew** [comment]
You mean the finetuning config? The finetuning configs are released at the [bevdet folder](https://github.com/Sense-X/GeoMIM/tree/main/bevdet/configs/bevdet_geomim).

**Comment by Wangzz12138** [comment]
Thank you for your answer, I have found the files.
